package lowlevel

/*
#include <fmod.h>
*/
import "C"
import "errors"

var ErrNoImpl = errors.New("Not implement yet")
var errs map[C.FMOD_RESULT]error

func init() {
	errs = map[C.FMOD_RESULT]error{
		C.FMOD_OK:                            nil,
		C.FMOD_ERR_BADCOMMAND:                errors.New("Tried to call a function on a data type that does not allow this type of functionality (ie calling Sound::lock on a streaming sound)."),
		C.FMOD_ERR_CHANNEL_ALLOC:             errors.New("Error trying to allocate a channel."),
		C.FMOD_ERR_CHANNEL_STOLEN:            errors.New("The specified channel has been reused to play another sound."),
		C.FMOD_ERR_DMA:                       errors.New("DMA Failure.  See debug output for more information."),
		C.FMOD_ERR_DSP_CONNECTION:            errors.New("DSP connection error.  Connection possibly caused a cyclic dependency or connected dsps with incompatible buffer counts."),
		C.FMOD_ERR_DSP_DONTPROCESS:           errors.New("DSP return code from a DSP process query callback.  Tells mixer not to call the process callback and therefore not consume CPU.  Use this to optimize the DSP graph."),
		C.FMOD_ERR_DSP_FORMAT:                errors.New("DSP Format error.  A DSP unit may have attempted to connect to this network with the wrong format, or a matrix may have been set with the wrong size if the target unit has a specified channel map."),
		C.FMOD_ERR_DSP_INUSE:                 errors.New("DSP is already in the mixer's DSP network. It must be removed before being reinserted or released."),
		C.FMOD_ERR_DSP_NOTFOUND:              errors.New("DSP connection error.  Couldn't find the DSP unit specified."),
		C.FMOD_ERR_DSP_RESERVED:              errors.New("DSP operation error.  Cannot perform operation on this DSP as it is reserved by the system."),
		C.FMOD_ERR_DSP_SILENCE:               errors.New("DSP return code from a DSP process query callback.  Tells mixer silence would be produced from read, so go idle and not consume CPU.  Use this to optimize the DSP graph."),
		C.FMOD_ERR_DSP_TYPE:                  errors.New("DSP operation cannot be performed on a DSP of this type."),
		C.FMOD_ERR_FILE_BAD:                  errors.New("Error loading file."),
		C.FMOD_ERR_FILE_COULDNOTSEEK:         errors.New("Couldn't perform seek operation.  This is a limitation of the medium (ie netstreams) or the file format."),
		C.FMOD_ERR_FILE_DISKEJECTED:          errors.New("Media was ejected while reading."),
		C.FMOD_ERR_FILE_EOF:                  errors.New("End of file unexpectedly reached while trying to read essential data (truncated?)."),
		C.FMOD_ERR_FILE_ENDOFDATA:            errors.New("End of current chunk reached while trying to read data."),
		C.FMOD_ERR_FILE_NOTFOUND:             errors.New("File not found."),
		C.FMOD_ERR_FORMAT:                    errors.New("Unsupported file or audio format."),
		C.FMOD_ERR_HEADER_MISMATCH:           errors.New("There is a version mismatch between the FMOD header and either the FMOD Studio library or the FMOD Low Level library."),
		C.FMOD_ERR_HTTP:                      errors.New("A HTTP error occurred. This is a catch-all for HTTP errors not listed elsewhere."),
		C.FMOD_ERR_HTTP_ACCESS:               errors.New("The specified resource requires authentication or is forbidden."),
		C.FMOD_ERR_HTTP_PROXY_AUTH:           errors.New("Proxy authentication is required to access the specified resource."),
		C.FMOD_ERR_HTTP_SERVER_ERROR:         errors.New("A HTTP server error occurred."),
		C.FMOD_ERR_HTTP_TIMEOUT:              errors.New("The HTTP request timed out."),
		C.FMOD_ERR_INITIALIZATION:            errors.New("FMOD was not initialized correctly to support this function."),
		C.FMOD_ERR_INITIALIZED:               errors.New("Cannot call this command after System::init."),
		C.FMOD_ERR_INTERNAL:                  errors.New("An error occurred that wasn't supposed to.  Contact support."),
		C.FMOD_ERR_INVALID_FLOAT:             errors.New("Value passed in was a NaN, Inf or denormalized float."),
		C.FMOD_ERR_INVALID_HANDLE:            errors.New("An invalid object handle was used."),
		C.FMOD_ERR_INVALID_PARAM:             errors.New("An invalid parameter was passed to this function."),
		C.FMOD_ERR_INVALID_POSITION:          errors.New("An invalid seek position was passed to this function."),
		C.FMOD_ERR_INVALID_SPEAKER:           errors.New("An invalid speaker was passed to this function based on the current speaker mode."),
		C.FMOD_ERR_INVALID_SYNCPOINT:         errors.New("The syncpoint did not come from this sound handle."),
		C.FMOD_ERR_INVALID_THREAD:            errors.New("Tried to call a function on a thread that is not supported."),
		C.FMOD_ERR_INVALID_VECTOR:            errors.New("The vectors passed in are not unit length, or perpendicular."),
		C.FMOD_ERR_MAXAUDIBLE:                errors.New("Reached maximum audible playback count for this sound's soundgroup."),
		C.FMOD_ERR_MEMORY:                    errors.New("Not enough memory or resources."),
		C.FMOD_ERR_MEMORY_CANTPOINT:          errors.New("Can't use FMOD_OPENMEMORY_POINT on non PCM source data, or non mp3/xma/adpcm data if FMOD_CREATECOMPRESSEDSAMPLE was used."),
		C.FMOD_ERR_NEEDS3D:                   errors.New("Tried to call a command on a 2d sound when the command was meant for 3d sound."),
		C.FMOD_ERR_NEEDSHARDWARE:             errors.New("Tried to use a feature that requires hardware support."),
		C.FMOD_ERR_NET_CONNECT:               errors.New("Couldn't connect to the specified host."),
		C.FMOD_ERR_NET_SOCKET_ERROR:          errors.New("A socket error occurred.  This is a catch-all for socket-related errors not listed elsewhere."),
		C.FMOD_ERR_NET_URL:                   errors.New("The specified URL couldn't be resolved."),
		C.FMOD_ERR_NET_WOULD_BLOCK:           errors.New("Operation on a non-blocking socket could not complete immediately."),
		C.FMOD_ERR_NOTREADY:                  errors.New("Operation could not be performed because specified sound/DSP connection is not ready."),
		C.FMOD_ERR_OUTPUT_ALLOCATED:          errors.New("Error initializing output device, but more specifically, the output device is already in use and cannot be reused."),
		C.FMOD_ERR_OUTPUT_CREATEBUFFER:       errors.New("Error creating hardware sound buffer."),
		C.FMOD_ERR_OUTPUT_DRIVERCALL:         errors.New("A call to a standard soundcard driver failed, which could possibly mean a bug in the driver or resources were missing or exhausted."),
		C.FMOD_ERR_OUTPUT_FORMAT:             errors.New("Soundcard does not support the specified format."),
		C.FMOD_ERR_OUTPUT_INIT:               errors.New("Error initializing output device."),
		C.FMOD_ERR_OUTPUT_NODRIVERS:          errors.New("The output device has no drivers installed.  If pre-init, FMOD_OUTPUT_NOSOUND is selected as the output mode.  If post-init, the function just fails."),
		C.FMOD_ERR_PLUGIN:                    errors.New("An unspecified error has been returned from a plugin."),
		C.FMOD_ERR_PLUGIN_MISSING:            errors.New("A requested output, dsp unit type or codec was not available."),
		C.FMOD_ERR_PLUGIN_RESOURCE:           errors.New("A resource that the plugin requires cannot be found. (ie the DLS file for MIDI playback)"),
		C.FMOD_ERR_PLUGIN_VERSION:            errors.New("A plugin was built with an unsupported SDK version."),
		C.FMOD_ERR_RECORD:                    errors.New("An error occurred trying to initialize the recording device."),
		C.FMOD_ERR_REVERB_CHANNELGROUP:       errors.New("Reverb properties cannot be set on this channel because a parent channelgroup owns the reverb connection."),
		C.FMOD_ERR_REVERB_INSTANCE:           errors.New("Specified instance in FMOD_REVERB_PROPERTIES couldn't be set. Most likely because it is an invalid instance number or the reverb doesn't exist."),
		C.FMOD_ERR_SUBSOUNDS:                 errors.New("The error occurred because the sound referenced contains subsounds when it shouldn't have, or it doesn't contain subsounds when it should have.  The operation may also not be able to be performed on a parent sound."),
		C.FMOD_ERR_SUBSOUND_ALLOCATED:        errors.New("This subsound is already being used by another sound, you cannot have more than one parent to a sound.  Null out the other parent's entry first."),
		C.FMOD_ERR_SUBSOUND_CANTMOVE:         errors.New("Shared subsounds cannot be replaced or moved from their parent stream, such as when the parent stream is an FSB file."),
		C.FMOD_ERR_TAGNOTFOUND:               errors.New("The specified tag could not be found or there are no tags."),
		C.FMOD_ERR_TOOMANYCHANNELS:           errors.New("The sound created exceeds the allowable input channel count.  This can be increased using the 'maxinputchannels' parameter in System::setSoftwareFormat."),
		C.FMOD_ERR_TRUNCATED:                 errors.New("The retrieved string is too long to fit in the supplied buffer and has been truncated."),
		C.FMOD_ERR_UNIMPLEMENTED:             errors.New("Something in FMOD hasn't been implemented when it should be! contact support!"),
		C.FMOD_ERR_UNINITIALIZED:             errors.New("This command failed because System::init or System::setDriver was not called."),
		C.FMOD_ERR_UNSUPPORTED:               errors.New("A command issued was not supported by this object.  Possibly a plugin without certain callbacks specified."),
		C.FMOD_ERR_VERSION:                   errors.New("The version number of this file format is not supported."),
		C.FMOD_ERR_EVENT_ALREADY_LOADED:      errors.New("The specified bank has already been loaded."),
		C.FMOD_ERR_EVENT_LIVEUPDATE_BUSY:     errors.New("The live update connection failed due to the game already being connected."),
		C.FMOD_ERR_EVENT_LIVEUPDATE_MISMATCH: errors.New("The live update connection failed due to the game data being out of sync with the tool."),
		C.FMOD_ERR_EVENT_LIVEUPDATE_TIMEOUT:  errors.New("The live update connection timed out."),
		C.FMOD_ERR_EVENT_NOTFOUND:            errors.New("The requested event, bus or vca could not be found."),
		C.FMOD_ERR_STUDIO_UNINITIALIZED:      errors.New("The Studio::System object is not yet initialized."),
		C.FMOD_ERR_STUDIO_NOT_LOADED:         errors.New("The specified resource is not loaded, so it can't be unloaded."),
		C.FMOD_ERR_INVALID_STRING:            errors.New("An invalid string was passed to this function."),
		C.FMOD_ERR_ALREADY_LOCKED:            errors.New("The specified resource is already locked."),
		C.FMOD_ERR_NOT_LOCKED:                errors.New("The specified resource is not locked, so it can't be unlocked."),
	}
}
